spring:
  application:
    name: spring-boot
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-boot;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

server:
  servlet:
    context-path: /app
